version: 2.1

orbs:
  node: circleci/node@4.2.1
  win: circleci/windows@2.4.0

default-root-dir: &default-root-dir
  working_directory: ~/project/disk

# Executors
# I declared multi platform and hope that testcase pass all system and work perfect with it
executors:
  base-executor:
    <<: *default-root-dir
    docker:
      - image: cimg/base:stable
  ubuntu-docker-common-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:18.04
  ubuntu-docker-oldest-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:14.04
  ubuntu-docker-latest-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:latest
  ubuntu-machine-executor:
    <<: *default-root-dir
    machine:
      image: ubuntu-2004:202010-01

# Command
commands:
  restore-cache-cmd:
    steps:
      - restore_cache:
          keys:
            - v1-disk-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-disk-{{ .Branch }}-
            - v1-disk-
  save-cache-cmd:
    steps:
      - save_cache:
          key: v1-disk-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  persist-to-workspace-cmd:
    steps:
      - persist_to_workspace:
          root: ~/project
          paths:
            - disk
  install-curl-cmd:
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y curl
  example-cmd:
    steps:
      - run: yarn ts-node-dev examples/lib.ts

  base-install-dependencies:
    parameters:
      install-application-commands:
        type: steps
        default: []
      persist-to-workspace:
        type: boolean
        default: true
    steps:
      - steps: << parameters.install-application-commands >>
      - checkout
      - restore-cache-cmd
      - run: yarn
      - save-cache-cmd
      - when:
          condition: << parameters.persist-to-workspace >>
          steps:
            - persist-to-workspace-cmd

  base-run-command:
    parameters:
      install-application-commands:
        type: steps
        default: []
      commands:
        type: steps
        default: []
    steps:
      - steps: << parameters.install-application-commands >>
      - attach_workspace:
          at: ~/project
      - steps: << parameters.commands >>

  win-install-nodejs-cmd:
    steps:
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: choco install nodejs-lts --version=12.22.0
      - run: choco install yarn
  win-install-dependencies:
    steps:
      - checkout
      - restore-cache-cmd
      - win-install-nodejs-cmd
      - run: yarn
      - save-cache-cmd

# Jobs
jobs:
  base-install-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-install-dependencies:
          install-application-commands:
            - install-curl-cmd
            - node/install:
                install-yarn: true
      - run: ls -l
  base-examples-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-run-command:
          install-application-commands:
            - install-curl-cmd
            - node/install:
                install-yarn: true
          commands:
            - example-cmd

  win-install-job:
    executor: win/default
    steps:
      - unix-install-dependencies
  win-examples-job:
    executor: win/default
    steps:
      - base-examples
  win-demo:
    executor: win/default
    steps:
      - win-install

# Workflows
workflows:
  test-reusable:
    jobs:
      - base-install-job:
          executor: base-executor
      - base-examples-job:
          executor: base-executor
          requires:
            - base-install-job
  test-b:
    jobs:
      - base-install-job:
          executor: ubuntu-docker-common-executor
      - base-examples-job:
          executor: ubuntu-docker-common-executor
          requires:
            - base-install-job
  # test-c:
  #   jobs:
  #     - base-install-job:
  #         executor: ubuntu-machine-executor
  #     - base-examples-job:
  #         executor: ubuntu-machine-executor
  #         requires:
  #           - base-install-job
