version: 2.1

orbs:
  node: circleci/node@4.2.1
  win: circleci/windows@2.4.0

default-root-dir: &default-root-dir
  working_directory: ~/project

# Executors
# I declared multi platform and hope that testcase pass all system and work perfect with it
executors:
  base-executor:
    <<: *default-root-dir
    docker:
      - image: cimg/base:stable
  ubuntu-docker-common-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:18.04
  ubuntu-docker-oldest-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:14.04
  ubuntu-docker-latest-executor:
    <<: *default-root-dir
    docker:
      - image: ubuntu:latest
  ubuntu-machine-executor:
    <<: *default-root-dir
    machine:
      image: ubuntu-2004:202010-01
  win-docker-common-executor:
    <<: *default-root-dir
    docker:
      - image: mcr.microsoft.com/windows:1903

# Command
commands:
  restore-cache-cmd:
    steps:
      - restore_cache:
          keys:
            - v1-disk-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-disk-{{ .Branch }}-
            - v1-disk-
  save-cache-cmd:
    steps:
      - save_cache:
          key: v1-disk-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  persist-to-workspace-cmd:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  install-curl-cmd:
    steps:
      - run: |
          if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
          $SUDO apt-get update > /dev/null 2>&1 || apt-get update > /dev/null 2>&1
          $SUDO apt-get install -y curl > /dev/null 2>&1 || apt-get install -y curl > /dev/null 2>&1
  win-install-application-cmd:
    steps:
      - run: |
          $chocoLocation = "C:\ProgramData\Chocolatey"
          # if (Test-Path $chocoLocation -PathType leaf) if check file
          if (Test-Path $chocoLocation)
          {
            Write-Host "chocolatey is installed. Skip install chocolatey";
          }
          else {
            Write-Host "chocolatey is NOT installed.";
            Set-ExecutionPolicy Bypass -Scope Process -Force;
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          }
      - run: |
          $CommandCheck = "node -v"
          $CommandInstall = "choco install nodejs-lts --version=12.22.0"
          try{
            $Version = Invoke-Expression $CommandCheck
            Write-Host $Version;
            Write-Host "Nodejs is installed. Skip install nodejs";
          }
          catch {
            Invoke-Expression $CommandInstall
          }
      - run: |
          $CommandCheck = "yarn -v"
          $CommandInstall = "choco install yarn"
          try{
            $Version = Invoke-Expression $CommandCheck
            Write-Host $Version;
            Write-Host "Yarn is installed. Skip install nodejs";
          }
          catch {
            Invoke-Expression $CommandInstall
          }
  example-cmd:
    steps:
      - run: yarn ts-node-dev examples/lib.ts

  base-install-dependencies:
    parameters:
      install-application-commands:
        type: steps
        default: []
    steps:
      - steps: << parameters.install-application-commands >>
      - checkout
      - restore-cache-cmd
      - run: yarn
      - save-cache-cmd
      - persist-to-workspace-cmd

  base-run-command:
    parameters:
      install-application-commands:
        type: steps
        default: []
      commands:
        type: steps
        default: []
    steps:
      - steps: << parameters.install-application-commands >>
      - attach_workspace:
          at: ~/project
      - steps: << parameters.commands >>

# Jobs
jobs:
  unix-install-dependencies-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-install-dependencies:
          install-application-commands:
            - install-curl-cmd
            - node/install:
                install-yarn: true
  unix-run-command-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-run-command:
          install-application-commands:
            - install-curl-cmd
            - node/install:
                install-yarn: true
          commands:
            - example-cmd

  windows-install-dependencies-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-install-dependencies:
          install-application-commands:
            - win-install-application-cmd
  windows-run-command-job:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - base-run-command:
          install-application-commands:
            - win-install-application-cmd
          commands:
            - example-cmd

  windows-demo:
    executor: win-docker-common-executor
    steps:
      - run: pwd

# Workflows
workflows:
  # ubuntu-docker-common-executor-testing:
  #   jobs:
  #     - unix-install-dependencies-job:
  #         executor: ubuntu-docker-common-executor
  #     - unix-run-command-job:
  #         executor: ubuntu-docker-common-executor
  #         requires:
  #           - unix-install-dependencies-job

  # ubuntu-docker-oldest-executor-testing:
  #   jobs:
  #     - unix-install-dependencies-job:
  #         executor: ubuntu-docker-oldest-executor
  #     - unix-run-command-job:
  #         executor: ubuntu-docker-oldest-executor
  #         requires:
  #           - unix-install-dependencies-job

  # ubuntu-docker-latest-executor-testing:
  #   jobs:
  #     - unix-install-dependencies-job:
  #         executor: ubuntu-docker-latest-executor
  #     - unix-run-command-job:
  #         executor: ubuntu-docker-latest-executor
  #         requires:
  #           - unix-install-dependencies-job

  # ubuntu-machine-executor-testing:
  #   jobs:
  #     - unix-install-dependencies-job:
  #         executor: ubuntu-machine-executor
  #     - unix-run-command-job:
  #         executor: ubuntu-machine-executor
  #         requires:
  #           - unix-install-dependencies-job

  # base-executor-testing:
  #   jobs:
  #     - unix-install-dependencies-job:
  #         executor: base-executor
  #     - unix-run-command-job:
  #         executor: base-executor
  #         requires:
  #           - unix-install-dependencies-job

  # windows-testing:
  #   jobs:
  #     - windows-install-dependencies-job:
  #         executor: win/default
  #     - windows-run-command-job:
  #         executor: win/default
  #         requires:
  #           - windows-install-dependencies-job

  windows-testing:
    jobs:
      - windows-demo
